<?php
if ($_SESSION['user']['role'] === 'admin'){

?>
<h1>Admin</h1>

<h2>Users Table:</h2>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>


<?php 

$query = $db->prepare('SELECT * FROM users');
$parameters = [
];
$query->execute($parameters);
$users = $query->fetchAll(PDO::FETCH_ASSOC);
foreach($users as $user){
    ?>
    <tr>
        <td><?=$user['id']?></td>
        <td><?=$user['email']?></td>
        <td><?=$user['first_name']?></td>
        <td><?=$user['last_name']?></td>
        <td><?=$user['role']?></td>
        <td><button>Modify</button><button>Delete</button></td>
    </tr>
    
    <?php
}}else{
  ?>
  <p>You have no admin rights !</p>
  <?php 
}
?>

</tbody>
</table>

<a href="./index.php?route=home">Back to Home</a>