<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <?php

    if ($route === null || preg_match("/home/", $route)) {
        require "home.phtml";
    } else if (preg_match("/inscription/", $route)) {
        require "register.phtml";
    } else if (preg_match("/connexion/", $route)) {
        require "login.phtml";
    } else if (preg_match("/logout/", $route)) {
        require "logout.phtml";
    } else if (preg_match("/admin/", $route)) {
        require "admin.phtml";
    }

    ?>

</body>

</html>