<h1>Register</h1>
<form action="./logic/register.php" method="post">
<label for="first_name">First Name:</label>
<input type="text" name="first_name" id="first_name">
<label for="last_name">Last Name:</label>
<input type="text" name="last_name" id="last_name">
<label for="email">Email:</label>
<input type="email" name="email" id="email">
<label for="password">Password:</label>
<input type="password" name="password" id="password">
<button type="submit">Submit
    <img src="https://media1.tenor.com/m/X7gCi8NE_h4AAAAd/cat-funny.gif" alt="" style="width:50px;">
</button>
</form>